- name: DISABLE ROOT ACCOUNT
  include_tasks: root_disable.yml

- name: ENABLE NON-FREE REPOS
  include_tasks: repo.yml

- name: INSTALL PACKAGES
  include_tasks: packages.yml

- name: INSTALL FLATPAK APPS
  include_tasks: flatpak.yml

- name: INSTALL PIPX PACKAGES
  include_tasks: pipx.yml

- name: COPY CONFIG FILES
  include_tasks: config.yml
