- name: Install Packages
  ansible.builtin.apt:
    name: "{{ package_install }}"
  become: true

- name: Remove Packages
  ansible.builtin.apt:
    name: "{{ package_remove }}"
    state: absent
  become: true

- name: Enable and run unattended-upgrades in systemd
  ansible.builtin.systemd_service:
    name: unattended-upgrades.service
    state: started
    enabled: true
  become: true
