package_install:
  - wget
  - tmux
  - neovim
  - unattended-upgrades
  - btop
  - git
  - curl
  - pipx
  - rsync
  - trash-cli
  - imagemagick
  - gparted
  - nmap
  - ttf-mscorefonts-installer
  - audacity
  - tree
  - pdftk
  - gobuster
  - feroxbuster
  - seclists
  - ewf-tools
  - gimp
  - libreoffice
  - cyberchef
  - openjdk-21-jdk
  - ghidra
  - gdb
  - zbar-tools
  - ncat
  - firmware-atheros
  - stepic
  - steghide
  - tcpflow
  - gnome-shell-extension-workspace-indicator
  - lz4
  - file
  - netcat-traditional
  - binwalk
  - foremost
  - exiftool
  - zip
  - unzip
  - bzip2
  - xz-utils
  - lzip
  - liblzo2-2
  - liblzma5
  - hydra
  - binutils
  - openssh-client
  - readpe
  - build-essential
  - python3
  - python3-venv
  - python3-pip
  - python3-dev
  - cmake
  - pkg-config
  - libssl-dev
  - libffi-dev
  - libtool
  - automake
  - autoconf
  - default-jre
  - fastfetch
  - wireshark
  - tcpdump
  - htop
  - netcat-openbsd
  - socat
  - rlwrap
  - hexedit
  - p7zip-full
  - john
  - john-data
  - hashcat
  - xxd
  - openssl
  - sqlmap
  - nikto
  - dirb
  - wafw00f
  - whatweb
  - httpie
  - burpsuite
  - zaproxy
  - pngcheck
  - ffmpeg
  - fcrackzip
  - sonic-visualiser
  - libjpeg-dev
  - ruby
  - ruby-dev
  - libc6-dbg
  - qemu-user
  - qemu-system
  - patchelf
  - nasm
  - gdb-multiarch
  - radare2
  - valgrind
  - strace
  - ltrace
  - jadx

package_remove:

firewall:
  - firewalld
  - firewall-config

clamav:
  - clamav
  - clamav-daemon
  - clamtk

superuser: jeiya
