package_install:
  - wget
  - tmux
  - neovim
  - unattended-upgrades
  - btop
  - git
  - curl
  - pipx
  - rsync
  - trash-cli
  - imagemagick
  - gparted
  - nmap
  - ttf-mscorefonts-installer
  - handbrake
  - audacity
  - tree
  - pdftk
  - gobuster
  - feroxbuster
  - seclists
  - ewf-tools
  - gimp
  - libreoffice
  - cyberchef
  - openjdk-21-jdk
  - ghidra
  - gdb
  - zbar-tools
  - ncat
  - firmware-atheros
  - stepic
  - steghide
  - outguess
  - tcpflow
  - gnome-shell-extension-workspace-indicator
  - lz4

package_remove:

firewall:
  - firewalld
  - firewall-config

clamav:
  - clamav
  - clamav-daemon
  - clamtk

superuser: jeiya
