package_install:
  - nala
  - tmux
  - neovim
  - unattended-upgrades
  - htop
  - btop
  - git
  - curl
  - pipx
  - rsync
  - shellcheck
  - bibata-cursor-theme
  - papirus-icon-theme
  - celluloid
  - trash-cli
  - fonts-roboto
  - piper
  - fping
  - uxplay
  - imagemagick
  - gparted
  - nmap
  - psensor
  - adb
  - ttf-mscorefonts-installer
  - easytag
  - f3
  - gnome-shell-extensions
  - gnome-shell-extension-manager
  - gnome-shell-extension-launch-new-instance
  - tree
  - pdftk
  - img2pdf
  - figlet
  - zip
  - fastfetch
  - chromium
  - transmission
  - ssh-askpass
  - python3
  - python3-pip
  - python3-venv
  - build-essential
  - python3-dev
  - gdb
  - gdb-doc
  - gdb-multiarch
  - radare2
  - valgrind
  - strace
  - ltrace
  - ghidra
  - jadx
  - nasm
  - patchelf
  - forensics-all
  - forensics-extra
  - steghide
  - steghide-doc
  - stegseek
  - pngcheck
  - foremost
  - ffmpeg
  - fcrackzip
  - audacity
  - sonic-visualiser
  - ruby
  - ruby-dev
  - wireshark
  - tcpdump
  - netcat-openbsd
  - socat
  - rlwrap
  - hexedit
  - john
  - john-data
  - hashcat
  - xxd
  - openssl
  - sqlmap
  - nikto
  - feroxbuster
  - gobuster
  - ffuf
  - dirb
  - wafw00f
  - whatweb
  - hydra
  - httpie
  - burpsuite
  - zaproxy
  - cargo
  - pkg-config
  - libssl-dev

package_remove:
  - libreoffice-gtk3
  - libreoffice-base-core
  - libreoffice-core
  - libreoffice-common
  - gnome-contacts
  - totem
  - malcontent

pip_packages:
  - pwntools
  - pycryptodome
  - numpy
  - sympy
  - scapy
  - requests
  - flask
  - angr

venv_path: "/home/{{ ansible_env.SUDO_USER }}/venv"

system_flatpaks:
  - com.dec05eba.gpu_screen_recorder
  - com.obsproject.Studio
  - com.github.tchx84.Flatseal

user_flatpaks:
  - com.bitwarden.desktop
  - com.brave.Browser
  - com.github.marktext.marktext
  - com.github.tenderowl.frog
  - com.jetpackduba.Gitnuro
  - com.jgraph.drawio.desktop
  - com.zettlr.Zettlr
  - dev.lasheen.qr
  - org.gimp.GIMP
  - org.gimp.GIMP.HEIC
  - org.gnome.design.Contrast
  - org.localsend.localsend_app
  - org.onlyoffice.desktopeditors
  - xyz.xclicker.xclicker
