package_install:
  - nala
  - tmux
  - neovim
  - unattended-upgrades
  - btop
  - git
  - curl
  - pipx
  - rsync
  - shellcheck
  - bibata-cursor-theme
  - papirus-icon-theme
  - celluloid
  - trash-cli
  - fonts-roboto
  - piper
  - fping
  - uxplay
  - imagemagick
  - gparted
  - nmap
  - psensor
  - adb
  - ttf-mscorefonts-installer
  - easytag
  - f3
  - handbrake
  - gnome-shell-extensions
  - gnome-shell-extension-manager
  - gnome-shell-extension-launch-new-instance
  - tree
  - pdftk
  - img2pdf
  - figlet
  - zip
  - fastfetch
  - chromium
  - transmission
  - ssh-askpass

package_remove:
  - libreoffice-gtk3
  - libreoffice-base-core
  - libreoffice-core
  - libreoffice-common
  - gnome-contacts
  - totem
  - malcontent

clamav:
  - clamav
  - clamav-daemon
  - clamtk

docker:
  - docker.io
  - docker-compose

firewall:
  - firewalld
  - firewall-config

qemu:
  - qemu-utils
  - qemu-system-x86
  - libvirt-daemon-system
  - virt-manager
  - virt-viewer

superuser: jeiya
