- name: Install flatpak
  ansible.builtin.package:
    name: flatpak
    state: present

- name: Ensure Flathub system remote exists
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present
    method: system

- name: Ensure Flathub user remote exists
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present
    method: user

