- name: Install Zram-tools
  ansible.builtin.apt:
    name: zram-tools

- name: Change swappiness value to 10
  ansible.builtin.sysctl:
    name: vm.swappiness
    value: "10"
    state: present
    reload: yes
