package_install:
  - nala
  - tmux
  - neovim
  - unattended-upgrades
  - btop
  - git
  - curl
  - pipx
  - rsync
  - shellcheck
  - bibata-cursor-theme
  - papirus-icon-theme
  - celluloid
  - trash-cli
  - fonts-roboto
  - piper
  - fping
  - uxplay
  - imagemagick
  - gparted
  - nmap
  - psensor
  - adb
  - ttf-mscorefonts-installer
  - easytag
  - f3
  - handbrake
  - gnome-shell-extensions
  - gnome-shell-extension-manager
  - gnome-shell-extension-launch-new-instance
  - tree
  - pdftk
  - img2pdf
  - figlet
  - zip
  - fastfetch
  - chromium
  - transmission
  - ssh-askpass

package_remove:
  - libreoffice-gtk3
  - libreoffice-base-core
  - libreoffice-core
  - libreoffice-common
  - gnome-contacts
  - totem
  - malcontent

clamav:
  - clamav
  - clamav-daemon
  - clamtk

docker:
  - docker.io
  - docker-compose

firewall:
  - firewalld
  - firewall-config

qemu:
  - qemu-utils
  - qemu-system-x86
  - libvirt-daemon-system
  - virt-manager
  - virt-viewer

system_flatpaks:
  - com.dec05eba.gpu_screen_recorder
  - com.obsproject.Studio
  - com.github.tchx84.Flatseal

user_flatpaks:
  - com.bitwarden.desktop
  - com.brave.Browser
  - com.github.marktext.marktext
  - com.github.tenderowl.frog
  - com.jetpackduba.Gitnuro
  - com.jgraph.drawio.desktop
  - com.zettlr.Zettlr
  - dev.lasheen.qr
  - org.gimp.GIMP
  - org.gimp.GIMP.HEIC
  - org.gnome.design.Contrast
  - org.localsend.localsend_app
  - org.onlyoffice.desktopeditors
  - xyz.xclicker.xclicker
  - org.prismlauncher.PrismLauncher
  - page.codeberg.JakobDev.jdMacroPlayer
  - com.valvesoftware.Steam
  - org.mozilla.Thunderbird
  - org.kde.kdenlive
  - dev.vencord.Vesktop
  - fr.handbrake.ghb
