- name: INSTALL PACKAGES
  include_tasks: packages.yml

- name: INSTALL FLATPAK APPS
  include_tasks: flatpak.yml

- name: SETUP PYTHON ENV
  include_tasks: python.yml

- name: COPY CONFIG FILES
  include_tasks: config.yml
